### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by RobHofmann** [arthurkrupa/gree-hvac-mqtt-bridge#10]
Hi, 

First of all: sorry if this is the wrong place to create this topic.

I'm using hass.io (Raspberry Pi 3) for my Home Automation. I recently bought 2 AC's which support the Gree protocol.

Im trying to get your Module to work. I did the following things:
1. Install your addon through Hass.io Addon System
2. Set the settings to:
```
{
  "hvac_host": "192.168.2.24",
  "mqtt": {
    "broker_url": "mqtt://localhost",
    "topic_prefix": "home/greehvac"
  }
}
```

Note: 192.168.2.24 is the IP of one of my AC's

Last i added this config:
```
climate:
  - platform: mqtt

    # Change to whatever you want
    name: Zolderkamer HVAC

    # Change MQTT_TOPIC_PREFIX to what you've set in addon options
    current_temperature_topic: "home/greehvac/temperature/get"
    temperature_command_topic: "home/greehvac/temperature/set"
    temperature_state_topic: "home/greehvac/temperature/get"
    mode_state_topic: "home/greehvac/mode/get"
    mode_command_topic: "home/greehvac/mode/set"
    fan_mode_state_topic: "home/greehvac/fanspeed/get"
    fan_mode_command_topic: "home/greehvac/fanspeed/set"
    swing_mode_state_topic: "home/greehvac/swingvert/get"
    swing_mode_command_topic: "home/greehvac/swingvert/set"
    power_state_topic: "home/greehvac/power/get"
    power_command_topic: "home/greehvac/power/set"

    # Keep the following as is
    payload_off: 0
    payload_on: 1
    modes:
      - none
      - auto
      - cool
      - dry
      - fan
      - heat
    swing_modes:
      - default
      - full
      - fixedTop
      - fixedMidTop
      - fixedMid
      - fixedMidBottom
      - fixedBottom
      - swingBottom
      - swingMidBottom
      - swingMid
      - swingMidTop
      - swingTop
    fan_modes:
      - auto
      - low
      - mediumLow
      - medium
      - mediumHigh
      - high
```

With this first setup i do see the climate.zolderkamer_hvac, but it doesn't actually work.

The second thing i tried is install the Mosquitto broker from the Hass.io Addon system. Then started the Mosquitto broker and finally started your Gree Bridge Addon. In this setup I do not see the climate.zolderkamer_hvac at all.

Am I missing something?

**Comment by arthurkrupa** [comment]
There are a couple problems with your config, which result in no communication between the 3 components (Gree addon, MQTT broker, Hass.io).

You need to have a working MQTT broker with anonymous access. You can use the Hass.io [Mosquitto Broker](https://www.home-assistant.io/addons/mosquitto/) addon for that. For initial testing, try to use this minimal config:
```
{
  "plain": true,
  "ssl": false,
  "anonymous": true,
  "logins": [],
  "customize": {
    "active": false,
    "folder": "mosquitto"
  }
}
```

Next, change the MQTT config in your Hass.io `configuration.yaml` to this:
```
mqtt:
  broker: localhost
  port: 1883
  client_id: hassio
  keepalive: 60
```

Finally, put this in the Gree addon config (replace with correct IPs):
```
{
  "hvac_host": "YOUR.HVAC.IP.HERE",
  "mqtt": {
    "broker_url": "mqtt://YOUR.HASSIO.IP.HERE"
    "topic_prefix": "home/greehvac"
  }
}
```
