### ISSUE TITLE
Invalid Mode

### ISSUE THREAD

**Issue by knackrack615** [arthurkrupa/gree-hvac-mqtt-bridge#19]
Getting spammed with invalid mode after upgrading to 1.1.0

![image](https://user-images.githubusercontent.com/2822335/49945440-954b9000-fef5-11e8-9afa-cc43639504e5.png)

I have added the new configuration.yaml options according to the readme

```
climate office_ac:
  - platform: mqtt

    # Change to whatever you want
    name: Office AC

    # Change MQTT_TOPIC_PREFIX to what you've set in addon options
    current_temperature_topic: "officeac/temperature/get"
    temperature_command_topic: "officeac/temperature/set"
    temperature_state_topic: "officeac/temperature/get"
    mode_state_topic: "officeac/mode/get"
    mode_command_topic: "officeac/mode/set"
    fan_mode_state_topic: "officeac/fanspeed/get"
    fan_mode_command_topic: "officeac/fanspeed/set"
    swing_mode_state_topic: "officeac/swingvert/get"
    swing_mode_command_topic: "officeac/swingvert/set"
    power_state_topic: "officeac/power/get"
    power_command_topic: "officeac/power/set"

    # Keep the following as is
    payload_off: 0
    payload_on: 1
    mode_state_template: "{{ value_json }}"
    modes:
      - "off"
      - "auto"
      - "cool"
      - "heat"
      - "dry"
      - "fan_only"
    swing_modes:
      - "default"
      - "full"
      - "fixedTop"
      - "fixedMidTop"
      - "fixedMid"
      - "fixedMidBottom"
      - "fixedBottom"
      - "swingBottom"
      - "swingMidBottom"
      - "swingMid"
      - "swingMidTop"
      - "swingTop"
    fan_modes:
      - "auto"
      - "low"
      - "mediumLow"
      - "medium"
      - "mediumHigh"
      - "high"
```
