### ISSUE TITLE
Using an automation, climate always comes on a 20deg auto

### ISSUE THREAD

**Issue by dragonflyuk** [arthurkrupa/gree-hvac-mqtt-bridge#28]
I've been trying to automate the AC to pre-heat our living room in the morning, however, it always come on at 20deg Auto mode hear is my code.

`- alias: Pre-heat Living Room
  initial_state: 'on'
  trigger:
    platform: time
    at: '05:45:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.living_room_ac
        temperature: 18
        operation_mode: Heat
`

Not sure if the issue is mqtt-bride, hassio, or possibly the thermostat control I have on my dashboard.

**Comment by arthurkrupa** [comment]
Maybe try using quotes on your YAML for the operation mode. Maybe that's why it defaults to Auto:
```yaml
- alias: 'Pre-heat Living Room'
  initial_state: 'on'
  trigger:
    platform: time
      at: '05:45:00'
      action:
        - service: climate.set_temperature
          data:
            entity_id: climate.living_room_ac
            temperature: 18
            operation_mode: 'Heat'
```
